# Additional data for chezmoi
rootConfigFolder = "slash"

# Maple Mono is the standard Maple Mono with double width icons
terminalFont = "Maple Mono NF CN"
terminalFontSize = 12

# Maple Mono NFMono is Maple Mono with single width icons (Nerd Fonts Mono)
monoFont = "Maple Mono NFMono CN"

# Maple Mono NFPropo is Maple Mono with variable width icons (Nerd Fonts Propo)
guiFont = "Maple Mono NFPropo CN"

# The icon theme used
iconTheme = "kora"

# The cursor theme used
cursorTheme = "Hacked-Sky-Cursor"
cursorSize = 24

# The default terminal
defaultTerminal = "ghostty"

# The window corner radius for Niri
windowCornerRadius = 8
